### ISSUE TITLE
Collision Boxes aren't scaling to the object size.

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#11]
Pic: 
![screen shot 2017-03-01 at 12 22 09 pm](https://cloud.githubusercontent.com/assets/6252212/23474569/d42d988c-fe79-11e6-9def-7dc133a549d4.png)

Is it that the collisionWidth and Height don't scale, but the points do? Or is just nothing scaling?

**Comment by runningcrane** [comment]
That's not good, the collision points should be scaling. At least, in the getJSON() of Platform, they're being multiplied by the scale value. If this is still an issue I will look into it.

**Comment by BryceStevenWilley** [comment]
Idk what this was, haven't had an issues with it again from what I remember. If it was an issue, then it shouldn't be after the refactor.
