### ISSUE TITLE
In the Collision Editor, the collision points aren't lined up after loading.

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#12]
![screenshot from 2017-03-03 11-54-32](https://cloud.githubusercontent.com/assets/6252212/23562505/51443b3e-0008-11e7-852d-702118b5ee79.png)

**Comment by runningcrane** [comment]
I've noticed this and that pressing Load a second time puts them in the right part. I haven't done serious debugging on it yet; thanks for bringing it up.

**Comment by BryceStevenWilley** [comment]
The workaround handles it well, so this isn't a huge deal.
