### ISSUE TITLE
Need directions on LevelEndX andY.

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#3]
Having a levelEndX and levelEndY is awesome, but depending on where the characters are moving at the end of the level, the end needs to either be greater than or less than that coordinate. For example, if the level end is at the bottom of the level, there needs to be an indication that the level should end when the character reaches a Y **less than** the levelEndY.

**Comment by runningcrane** [comment]
Acknowledged.

**Comment by BryceStevenWilley** [comment]
Included in #17.
