### ISSUE TITLE
Make output JSON readible

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#4]
Super low priority, but it does make debugging so much easier.  Really just need to add newlines after arrays, objects, and members.

**Comment by runningcrane** [comment]
I am not sure if this is possible in JSONSimple, but I will look into it.

**Comment by BryceStevenWilley** [comment]
Implemented in 62a16d502341dff4503b55fd6ce40cb7db03e358 with the addition of GSON.
