### ISSUE TITLE
Make the mToPixel value a slider.

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#5]
I recently realized that the mToPixel value is worthless on the cocos side, as it changes the mass of the characters and messes up their movement physics.  However, the mToPixel in the level editor is really useful for zooming in and out on the level you're making, and it would be easier to use as a zoom slider, since the exact value doesn't matter during gameplay.

**Comment by runningcrane** [comment]
Acknowledged.

**Comment by BryceStevenWilley** [comment]
Fixed with commit 4c81795d596f32, I believe.
