### ISSUE TITLE
Add support for polygonal boulders.

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#6]
From Mei's designs, we'll have to support non-circular boulders. This shouldn't be difficult, as the mechanisms to handle polygonal shapes already exist for platforms. 

However, we'll still need to eventually support circular boulders, as it's pretty hard to 
roll polygons. I'm imagining a checkbox for circle/polygon, and if circle, just give radius, and if 
polygon, give the points as you would in a platform.

I'll write what I need in the skeletonJson.txt soon and post here when I do.

**Comment by runningcrane** [comment]
Thanks. Please do.

**Comment by BryceStevenWilley** [comment]
Done a long time ago, haha.
