### ISSUE TITLE
Separation of Visual Objects and Interactables

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#7]
Right now, we're defining all things on the screen as a platform of some kind or another, even if they are just there for visual purposes. However, the game expects all platforms to have collision points. If I forget to add some collision points to an object, the game will freak out, because it can't define a platform without collision information about that platform. 

How do we solve this? Should it be split into visual/interactables across the board for both projects, should there be better tools for adding dummy collision boxes to all objects in the level editor, or should the game be able to handle platforms without collision boxes gracefully?

**Comment by runningcrane** [comment]
Fixed with the collidable checkbox update.
