### ISSUE TITLE
Can't remove objects once added to the Scene? 

### ISSUE THREAD

**Issue by BryceStevenWilley** [runningcrane/JTTWLevelEditor#9]
I can't see where to do that.

**Comment by runningcrane** [comment]
Should be in the LayerWindow; there's a red remove button for each object.

**Comment by BryceStevenWilley** [comment]
Ah, I see what it is: setting the background doesn't work on macs, and setting the font to white would make the font dissappear, so looked like a button with no text to me. Fixed it with this: http://stackoverflow.com/questions/1065691/how-to-set-the-background-color-of-a-jbutton-on-the-mac-os, even the button looks a little dumb now, but at least useable.
